apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherweb-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: weatherweb
  template:
    metadata:
      labels:
        app: weatherweb
    spec:
      containers:
      - name: weatherweb-container
        image: marcelino30/weatherwebproject:latest 
        ports:
        - containerPort: 80
      - name: sidecar-container
        image: busybox
        args: ["sh", "-c", "while true; do echo 'Sidecar container is running'; sleep 10; done"]
